version: '3.1'

services:
  espresso-database:
    container_name: espresso-database
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

# TODO: add pgadmin
